image: hseeberger/scala-sbt:11.0.1_2.12.8_1.2.7

before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  # Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update -y
  - apt-get install sbt=0.13.8 -y
  - sbt sbtVersion

test:
  script:
    - SBT_OPTS="-Xmx4G" sbt clean compile test:compile
